DROP TABLE IF EXISTS Task;
CREATE TABLE IF NOT EXISTS `Task` (
 `id` BIGINT NOT NULL AUTO_INCREMENT,
 `user_id` BIGINT NOT NULL,
 `text` VARCHAR(4000) NOT NULL,
 `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (`id`)
) ENGINE = InnoDB;