version: '3.8'
services:
  db:
    container_name: bbb-db-mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./test_db:/var/lib/mysql
      - ./custom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - 3306:3306

  cache:
    container_name: bbb-cache-redis
    image: redis:latest
